extends:
  - standard
  - standard-react
  - plugin:import/recommended
  - plugin:jsx-a11y/recommended
  - plugin:monorepo/recommended
  - plugin:promise/recommended
  - plugin:ramda/recommended
  - plugin:react/recommended
  - plugin:unicorn/recommended
  - prettier
  - prettier/react
  - prettier/standard
globals:
  __DEV__: false
overrides:
  - files:
      - '**/*.ts?(x)'
      - '.*/**/*.ts?(x)'
    parser: '@typescript-eslint/parser'
    parserOptions:
      project: ./tsconfig.json
    plugins:
      - '@typescript-eslint'
    rules:
      no-array-constructor: off
      no-unused-vars: off
      no-use-before-define: off
      '@typescript-eslint/adjacent-overload-signatures': error
      '@typescript-eslint/array-type': error
      '@typescript-eslint/ban-types': error
      '@typescript-eslint/class-name-casing': error
      '@typescript-eslint/interface-name-prefix': error
      '@typescript-eslint/no-angle-bracket-type-assertion': error
      '@typescript-eslint/no-array-constructor': error
      '@typescript-eslint/no-empty-interface': error
      '@typescript-eslint/no-inferrable-types': error
      '@typescript-eslint/no-misused-new': error
      '@typescript-eslint/no-namespace': error
      '@typescript-eslint/no-non-null-assertion': error
      '@typescript-eslint/no-object-literal-type-assertion': error
      '@typescript-eslint/no-parameter-properties': error
      '@typescript-eslint/no-triple-slash-reference': error
      '@typescript-eslint/no-unused-vars': warn
      '@typescript-eslint/no-use-before-define': error
      '@typescript-eslint/no-var-requires': error
      '@typescript-eslint/prefer-interface': error
      '@typescript-eslint/prefer-namespace-keyword': error
      '@typescript-eslint/type-annotation-spacing': error
  - files:
      - 'config/cypress/**/*.?(js|ts)'
      - 'test/**/*.ts?(x)'
    env:
      browser: true
      mocha: true
    globals:
      Cypress: true
      assert: true
      cy: true
      expect: true
    plugins:
      - cypress
    rules:
      cypress/no-assigning-return-values: error
      cypress/no-unnecessary-waiting: error
  - files:
      - 'config/jest/**/*.?(js|ts)'
      - 'src/**/?(*.)test.ts?(x)'
    env:
      jest: true
    globals:
      __DEV__: true
    plugins:
      - jest
    rules:
      jest/no-alias-methods: warn
      jest/no-disabled-tests: warn
      jest/no-focused-tests: error
      jest/no-identical-title: error
      jest/no-jasmine-globals: warn
      jest/no-jest-import: error
      jest/no-test-prefixes: error
      jest/valid-describe: error
      jest/valid-expect-in-promise: error
      jest/valid-expect: error
plugins:
  - import
  - jsx-a11y
  - monorepo
  - prettier
  - promise
  - ramda
  - react
  - standard
  - unicorn
rules:
  no-console:
    - error
    - allow:
        - error
        - info
        - warn
  no-param-reassign:
    - error
    - props: true
  prettier/prettier: error
settings:
  import/resolver:
    typescript: true
