extends:
  - standard
  - plugin:jest/recommended
  - plugin:monorepo/recommended
  - plugin:typescript/recommended
  - prettier
  - prettier/standard
overrides:
  - env:
      jest: true
    files:
      - '**/?(*.)test.ts?(x)'
    plugins:
      - jest
parser: eslint-plugin-typescript/parser
plugins:
  - import
  - monorepo
  - prettier
  - typescript
rules:
  no-console: error
  no-undef: error
  prettier/prettier: error
  typescript/explicit-member-accessibility: off
  typescript/indent:
    - error
    - 2
  typescript/member-delimiter-style: off
  typescript/member-ordering: error
  typescript/no-explicit-any: off
settings:
  import/resolver:
    typescript: true
