extends:
  - stylelint-config-standard
  - stylelint-config-styled-components
  - stylelint-config-prettier
plugins:
  - stylelint-order
processors:
  - stylelint-processor-styled-components
rules:
  declaration-empty-line-before:
    - never
    - ignore:
        - after-declaration
  order/order:
    - custom-properties
    - dollar-variables
    - declarations
    - at-rules
    - rules
