version: '3'
services:
  server:
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    image: fintruth/server:latest
    links:
      - database
    ports:
      - '3000:3000'
