version: '3'
services:
  client:
    build:
      context: .
      dockerfile: dockerfile.client
    image: fintruth/client:latest
    links:
      - server
    ports:
      - '3000:3000'
  server:
    build:
      context: .
      dockerfile: dockerfile.server
    image: fintruth/server:latest
    links:
      - database
    ports:
      - '4000:4000'
