version: '3'
services:
  database:
    image: postgres:10.6-alpine
    environment:
      POSTGRES_DB: fintruth
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    restart: always
