aliases:
  - &restore_cache
    keys:
      - dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - dependency-cache-{{ .Branch }}-
  - &save_cache
    key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
    paths:
      - node_modules
  - &store_report_artifacts
    destination: reports
    path: reports
  - &store_test_results
    path: reports/client

version: 2.1
commands:
  install_dependencies:
    description: Install dependencies
    paramters:
      options:
        type: string
        default:
    steps:
      - run: yarn install << paramters.options >>
executors:
  node-10:
    docker:
      - image: circleci/node:10.15.3
jobs:
  client:
    executor: node-10
    working_directory: ~/fintruth-sdk/packages/client
    steps:
      - checkout
      - restore_cache: *restore_cache
      - install_dependencies
      - save_cache: *save_cache
      - run:
          name: Setup
          command: mkdir --parents reports/client
      - run:
          name: Run static analysis
          command: |
            yarn --silent lint:scripts --format junit --output-file reports/client/lint-scripts-results.xml
            yarn --silent lint:styles --custom-formatter node_modules/stylelint-junit-formatter > reports/client/lint-styles-results.xml
            yarn --silent lint:types
      - run:
          name: Run tests
          command: yarn --silent test:units --runInBand --reporters default jest-junit
          environment:
            JEST_JUNIT_OUTPUT: reports/client/test-units-results.xml
      - store_artifacts: *store_report_artifacts
      - store_test_results: *store_test_results
workflows:
  version: 2.1
  test:
    jobs:
      - client
