aliases:
  - &restore_cache
    keys:
      - dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - dependency-cache-{{ .Branch }}-
  - &save_cache
    key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
    paths:
      - node_modules

version: 2.1
executors:
  node-10:
    docker:
      - image: circleci/node:10.15.3
jobs:
  client:
    environment:
      REPORTS_DIR: reports/client
      WORKING_DIR: packages/client
    executor: node-10
    working_directory: ~/fintruth-sdk
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache: *save_cache
      - run:
          name: Setup
          command: mkdir --parents ${REPORTS_DIR}
          working_directory: packages/client
      - run:
          name: Run static analysis
          command: yarn lint:scripts --format junit --output-file ${REPORTS_DIR}/lint-scripts-results.xml
          working_directory: packages/client
      - run:
          name: Run static analysis
          command: |
            echo ${CIRCLE_WORKING_DIRECTORY}
            yarn lint:styles --custom-formatter ../../node_modules/stylelint-junit-formatter > ${REPORTS_DIR}/lint-styles-results.xml
          working_directory: packages/client
      - run:
          name: Run static analysis
          command: yarn lint:types
          working_directory: packages/client
      - run:
          name: Run tests
          command: yarn --silent test:units --runInBand --reporters default jest-junit
          environment:
            JEST_JUNIT_OUTPUT: ${REPORTS_DIR}/test-units-results.xml
          working_directory: packages/client
      - store_artifacts:
          path: ${WORKING_DIR}/reports
          destination: reports
      - store_test_results:
          path: ${WORKING_DIR}/reports
workflows:
  version: 2.1
  test:
    jobs:
      - client
