version: 2.1
executors:
  node-10:
    docker:
      - image: circleci/node:10.15.3
jobs:
  shared:
    environment:
      REPORTS_DIR: reports/shared
    executor: node-10
    working_directory: ~/fintruth-sdk
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Setup
          command: mkdir --parents ${REPORTS_DIR}
          working_directory: packages/shared
      - run:
          name: Run static analysis
          command: |
            yarn lint:scripts --format junit --output-file ${REPORTS_DIR}/lint-scripts-results.xml
            yarn lint:types
          working_directory: packages/shared
      - run:
          name: Build
          command: yarn build
          working_directory: packages/shared
      - persist_to_workspace:
          root: .
          paths: packages/shared/build
      - store_artifacts:
          path: packages/shared/reports
          destination: reports
      - store_test_results:
          path: packages/shared/reports
  client:
    environment:
      REPORTS_DIR: reports/client
    executor: node-10
    working_directory: ~/fintruth-sdk
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Setup
          command: mkdir --parents ${REPORTS_DIR}
          working_directory: packages/client
      - run:
          name: Run static analysis
          command: |
            yarn lint:scripts --format junit --output-file ${REPORTS_DIR}/lint-scripts-results.xml
            yarn lint:styles --custom-formatter ${CIRCLE_WORKING_DIRECTORY}/node_modules/stylelint-junit-formatter > ${REPORTS_DIR}/lint-styles-results.xml
            yarn lint:types
          working_directory: packages/client
      - run:
          name: Run tests
          command: yarn --silent test:units --runInBand --reporters default jest-junit
          environment:
            JEST_JUNIT_OUTPUT: ${REPORTS_DIR}/test-units-results.xml
          working_directory: packages/client
      - store_artifacts:
          path: packages/client/reports
          destination: reports
      - store_test_results:
          path: packages/client/reports
workflows:
  version: 2.1
  test:
    jobs:
      - client
