aliases:
  - &restore_cache
    keys:
      - dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - dependency-cache-{{ .Branch }}-
  - &save_cache
    key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
    paths:
      - node_modules

version: 2.1
commands:
  install_dependencies:
    parameters:
      options:
        type: string
        default: ''
    steps:
      - run:
          name: Install dependencies
          command: yarn install << parameters.options >>
executors:
  node-10:
    docker:
      - image: circleci/node:10.15.3
jobs:
  client:
    environment:
      PACKAGE: '@fintruth-sdk/client'
      REPORTS_DIR: reports/client
      WORKING_DIR: packages/client
    executor: node-10
    working_directory: ~/fintruth-sdk
    steps:
      - checkout
      - restore_cache: *restore_cache
      - install_dependencies
      - save_cache: *save_cache
      - run:
          name: Setup
          command: |
            mkdir --parents ${REPORTS_DIR}
            pwd
            echo ${WORKING_DIR}
            ls -ahl
          working_directory: ${WORKING_DIR}
      - run:
          name: Run static analysis
          command: |
            yarn --silent lerna --loglevel silent run --scope ${PACKAGE} lint:scripts -- --format junit --output-file ${REPORTS_DIR}/lint-scripts-results.xml
            yarn --silent lerna --loglevel silent run --scope ${PACKAGE} lint:styles -- --custom-formatter node_modules/stylelint-junit-formatter > ${REPORTS_DIR}/lint-styles-results.xml
            yarn --silent lerna --loglevel silent run --scope ${PACKAGE} lint:types
      - run:
          name: Run tests
          command: yarn --silent lerna --loglevel silent run --scope ${PACKAGE} test:units -- --runInBand --reporters default jest-junit
          environment:
            JEST_JUNIT_OUTPUT: ${REPORTS_DIR}/test-units-results.xml
      - store_artifacts:
          path: ${WORKING_DIR}/reports
          destination: reports
      - store_test_results:
          path: ${WORKING_DIR}/reports
workflows:
  version: 2.1
  test:
    jobs:
      - client
