extends:
  - standard
  - plugin:jest/recommended
  - plugin:monorepo/recommended
  - plugin:typescript/recommended
  - prettier
  - prettier/standard
overrides:
  - env:
      jest: true
    files:
      - '**/?(*.)test.ts?(x)'
    plugins:
      - jest
    rules:
      jest/no-alias-methods: warn
      jest/no-disabled-tests: warn
      jest/no-focused-tests: error
      jest/no-identical-title: error
      jest/no-jasmine-globals: warn
      jest/no-jest-import: error
      jest/no-test-prefixes: error
      jest/valid-describe: error
      jest/valid-expect-in-promise: error
      jest/valid-expect: error
parser: eslint-plugin-typescript/parser
plugins:
  - import
  - monorepo
  - prettier
  - typescript
rules:
  no-console: error
  no-undef: error
  prettier/prettier: error
  typescript/explicit-member-accessibility: off
  typescript/indent:
    - error
    - 2
  typescript/member-delimiter-style: off
  typescript/member-ordering: error
  typescript/no-explicit-any: off
  typescript/no-unused-vars:
    - warn
    - argsIgnorePattern: ^_
settings:
  import/resolver:
    typescript: true
