version: '3'
services:
  database:
    image: postgres:10.6-alpine
    environment:
      POSTGRES_DB: database
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    networks:
      default:
    ports:
      - '5432:5432'
