type: postgres
host: localhost
username: postgres
password: postgres
port: 5432
database: database
logging: false
synchronize: true
cli:
  entitiesDir: src/entities
  migrationsDir: src/migrations
  subscribersDir: src/subscribers
entities:
  - src/entities/**/*.ts
migrations:
  - src/migrations/**/*.ts
subscribers:
  - src/subscribers/**/*.ts
