cli:
  entitiesDir: src/entities
  migrationsDir: src/migrations
  subscribersDir: src/subscribers
database: database
entities:
  - src/entities/**/*.ts
host: localhost
logging: false
migrations:
  - src/migrations/**/*.ts
password: postgres
port: 5432
subscribers:
  - src/subscribers/**/*.ts
synchronize: true
type: postgres
username: postgres
