type: postgres
host: localhost
database: database
username: postgres
password: postgres
port: 5432
synchronize: true
logging: false
cli:
  entitiesDir: src/entities
  migrationsDir: src/migrations
  subscribersDir: src/subscribers
entities:
  - src/entities/**/*.ts
migrations:
  - src/migrations/**/*.ts
subscribers:
  - src/subscribers/**/*.ts
