default:
  type: postgres
  host: localhost
  username: postgres
  password: postgres
  port: 5432
  database: fintruth
  cli:
    entitiesDir: src/entities
    migrationsDir: src/migrations
    subscribersDir: src/subscribers
  entities:
    - src/entities/*.ts
  migrations:
    - src/migrations/*.ts
  subscribers:
    - src/subscribers/*.ts
